### ISSUE TITLE
Lift off

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-minitest#1]
Here's a rundown of the things we need to do:

- [ ] Find some maintainers for the project
- [ ] Create a style guide documenting the best MiniTest practices
- [ ] Setup the basic project structure (it's should be based on the existing extensions like `rubocop-rspec` and `rubocop-rails`
- [ ] Hack and have fun

If you want to work on all/any of this - comment on this issue. 😉

**Comment by prathamesh-sonpatki** [comment]
I will take a stab at `Setup the basic project structure (it's should be based on the existing extensions like rubocop-rspec and rubocop-rails`

**Comment by coding-bunny** [comment]
As mentioned on Twitter, I'd be happy to help out on this project.
Looks like a nice step up from using RuboCop and reporting issues :D

**Comment by Springok** [comment]
We are using mintiest in our team, maybe I can help on the item about style guide, and I am also interested in setup of basic project structure, will check the ‘rubicon-rails’ first~

**Comment by bbatsov** [comment]
Btw - I've created an empty https://github.com/rubocop-hq/minitest-style-guide

**Comment by koic** [comment]
> Setup the basic project structure (it's should be based on the existing extensions like `rubocop-rspec` and `rubocop-rails`

One point. RuboCop minitest tests should be written by minitest, not RSpec. This makes RuboCop minitest itself dogfooding for RuboCop minitest.

Therefore basic project structure should be like that.

**Comment by coding-bunny** [comment]
Do we have any guide for minitest to start from?
Would be cool to identify some basic cops to create or something to work towards to

**Comment by bbatsov** [comment]
@coding-bunny I'm counting on those of you who use Minitest to document the best practices you know here https://github.com/rubocop-hq/minitest-style-guide I haven't used it myself in ages, so I can't help much there.

**Comment by coding-bunny** [comment]
Okay, so we're pretty much on a clean slate :)
I think we should stick to "clean" minitests approaches? The reason I'm asking is that at our company we usually include/enforce the usage of `minitest-spec-rails`, but I think if we want to write cops for that stuff specifically (mixture of minitest and rspec) we'll need a separate rubocop plugin.

So how shall we best start on this? Make PRs to update the style-guide first and establish what the best-practises are for everyone?

**Comment by bbatsov** [comment]
Yeah, I'd stick to the "clean" approaches and avoid framework-specific stuff.

**Comment by Springok** [comment]
> Do we have any guide for minitest to start from?
> Would be cool to identify some basic cops to create or something to work towards to

I think some rules in RSpec are also applied in Minitest, for example the `let` usage,  maybe we can start from there, migrate some rules from RSpec first?

**Comment by koic** [comment]
I opened a PR #3 to import a minimal implementation from RuboCop Performance/Rails for enable CircleCI. (I had to set up CI first 💦)
This repository can checked PRs by CircleCI. Please let me know if you have any problems.

Cc @prathamesh-sonpatki

**Comment by bbatsov** [comment]
Guess we can close this one. Potentially we can even cut 0.2 at this point. //cc @koic

**Comment by koic** [comment]
RuboCop 0.2 has been released and I will close this one.
https://github.com/rubocop-hq/rubocop-minitest/releases/tag/v0.2.0

**Comment by coding-bunny** [comment]
Sorry for the late feedback, but we're going to start using this gem in our internal RuboCop gem, so I hope this will bring up more stuff to talk about
