### ISSUE TITLE
Relax checking of test case

### ISSUE THREAD

**Issue by fatkodima** [rubocop-hq/rubocop-minitest#100]
Similar to https://github.com/rubocop-hq/rubocop-minitest/pull/99, I'm suggesting to identify test case as a method call, whose name starts with `assert_` or `refute_`. This will automatically work with custom assertions and rails' specific assertions.

https://github.com/rubocop-hq/rubocop-minitest/blob/85abdbea1853df82928daa90c29bb6203f418919/lib/rubocop/cop/mixin/minitest_exploration_helpers.rb#L70-L72

If sounds good, will submit a pr.

**Comment by koic** [comment]
Yeah, I think it's worth a try. Can you open a PR?
