### ISSUE TITLE
Error with Minitest/AssertOutput when global assignment occurs at top level

### ISSUE THREAD

**Issue by mvz** [rubocop-hq/rubocop-minitest#106]
If a file under `test/` contains an assignment to a global variable at the top level, Minitest/AssertOutput will generate an error

## Expected behavior

Minitest/AssertOutput ignores the assignment because it doesn't occur in a test case

## Actual behavior

RuboCop generates an error message like the following:

```
An error occurred while Minitest/AssertOutput cop was inspecting /home/matijs/Projects/gir_ffi/test/foo.rb:1:0
```

## Steps to reproduce the problem

Given a project configured for using rubocop-minitest, create a file `test/foo.rb` containing

```ruby
$VERBOSE = false
```

Then run:

```
$ rubocop test/foo.rb
```

## RuboCop version

```
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.7.1 x86_64-linux)
```

**Comment by mvz** [comment]
Thanks, @koic!

**Comment by koic** [comment]
@mvz You are welcome :-) Thank you for feedback!
