### ISSUE TITLE
Requiring 'rubocop-minitest' in config limits all cops to only run on the test/ directory

### ISSUE THREAD

**Issue by tayjohno** [rubocop-hq/rubocop-minitest#13]
First off, thanks for starting a minitest-specific repo! I'm very excited to incorporate this into our Rubocop install. I've noticed that while the current gems are already useful, there's a configuration conflict that's preventing us from being able to use this in its current state.

## Expected behavior

Adding the line
```
require:
  - rubocop-minitest
  ...
```
should not impact the configuration of existing cops.

## Actual behavior

When adding the above line, rubocop ceases to run on any files outside of our `/test/` directory. It appears that [this configuration](https://github.com/rubocop-hq/rubocop-minitest/blob/master/config/default.yml#L3) is overriding the default configuration for _all_ rubocop gems.

## Steps to reproduce the problem

See repo here for a simple reproduction of the issue.

https://github.com/tayjohno/sample-rubocop-minitest-issue 

When commenting out [the line to include `rubocop-minitest`](https://github.com/tayjohno/sample-rubocop-minitest-issue/blob/master/.rubocop.yml#L2), you'll see that the base rubocop gems run on 3 files (`Gemfile`, `lib/sample.rb`, and `test/sample_test.rb`).

```
$ [bundle exec] rubocop
Inspecting 3 files
.CC

Offenses:

lib/sample.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
class Sample
^
test/sample_test.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
class SampleTest < Minitest::Test
^
test/sample_test.rb:2:1: C: Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.

3 files inspected, 3 offenses detected
```

But when you uncomment the line, even the base rubocop cops _only_ runs on `test/sample_test.rb`.

```
$ [bundle exec] rubocop
Inspecting 1 file
C

Offenses:

test/sample_test.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
class SampleTest < Minitest::Test
^
test/sample_test.rb:2:1: C: Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.

1 file inspected, 2 offenses detected
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.74.0 (using Parser 2.6.4.1, running on ruby 2.6.2 x86_64-darwin18)
```

**Comment by koic** [comment]
Thanks for your early feedback using RuboCop Minitest!
I opened a PR #14 and  I will cut RuboCop Minitest 0.3 soon.

**Comment by koic** [comment]
RuboCop Minitest 0.2.1 has been released. Thanks again!
