### ISSUE TITLE
Unexpected "Warning: Minitest does not support Enabled parameter."

### ISSUE THREAD

**Issue by grzuy** [rubocop-hq/rubocop-minitest#25]
Hi,

Thank you for building this plugin!

Getting unexpected warning message when running rubocop with a rubocop config file in which I try to enable `Minitest` department.

Department gets enabled and `Minitest` cops run. The problem is the warning message only from what I can tell.

## Expected behavior

I wouldn't expect to get any warning message.

## Actual behavior

I get a warning message saying "Warning: Minitest does not support Enabled parameter."

## Steps to reproduce the problem

```
# .rubocop.yml
AllCops:
  DisabledByDefault: true

Minitest:
  Enabled: true
```

```
$ bundle exec rubocop
Warning: Minitest does not support Enabled parameter.

Supported parameters are:

  - Include

Inspecting 67 files
...................................................................

67 files inspected, no offenses detected
```

Reproduced in line `281` of https://travis-ci.org/kickstarter/rack-attack/jobs/596321353.

## RuboCop version

```
$ bundle exec rubocop -V
0.75.0 (using Parser 2.6.5.0, running on ruby 2.6.5 x86_64-linux)
```

**Comment by koic** [comment]
@pocke FYI, RuboCop Rake seems to have the same issue.

```console
% cat .rubocop.yml
require: rubocop-rake

AllCops:
  DisabledByDefault: true

Rake:
  Enabled: true

% rubocop
Warning: Rake does not support Enabled parameter.

Supported parameters are:

  - Include

Inspecting 0 files


0 files inspected, no offenses detected
```

**Comment by koic** [comment]
I opened a PR #33.

@pocke I'm sorry about RuboCop Rake, it is regressing with the PR https://github.com/rubocop-hq/rubocop-rake/pull/18. I will open a PR to RuboCop Rake repo if you are OK.
