### ISSUE TITLE
Minitest/AssertRespondTo autocorrect causes ArgumentError: wrong number of arguments (given 1, expected 2..3)

### ISSUE THREAD

**Issue by ccasabona** [rubocop-hq/rubocop-minitest#39]
Given the test statement:

`assert respond_to? :token_payment_method`

The Minitest/AssertRespond cop auto corrects that to 

`assert_respond_to(:token_payment_method)`

When the test is run, an error message is returned: 

`ArgumentError: wrong number of arguments (given 1, expected 2..3)`

The log message is

`[Corrected] Minitest/AssertRespondTo: Prefer using assert_respond_to(:token_payment_method) over assert(respond_to? :token_payment_method).`

Minitest assert_respond_to requires an object:

> assert_respond_to(obj, meth, msg = nil)

This can be corrected by editing the corrected test statement to:

`assert_respond_to(self, :token_payment_method)`

Using Rails 6.01, Ruby 2.65, Minitest 5.13.0

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #40.
