### ISSUE TITLE
Minitest/RefuteIncludes cop misses some bad use cases

### ISSUE THREAD

**Issue by senhalil** [rubocop-hq/rubocop-minitest#52]
The following 4 asserts should be marked as an offence per minitest-style-guide but they are not. 

```
class Test < Minitest::Test
    def mytest
        assert !(Foo.include? :bar)
        assert !Foo.include?(:bar)
        assert(!(Foo.include? :bar))
        assert(!Foo.include?(:bar))

        refute_includes(Foo, :bar)
    end
end
```
--------

## Expected behavior
Rubocop should mark the above asserts as an offence and suggest usage of `refute_includes`
https://github.com/rubocop-hq/minitest-style-guide#refute-includes

## Actual behavior
None of the offences got caught.
```
rubocop  --only Minitest ./test/rubocop-minitest_bug.rb 
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## Steps to reproduce the problem
Running rubocop on the example above returns no offences even though it should.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.79.0 (using Parser 2.7.0.2, running on ruby 2.3.8 x86_64-linux)
```

**Comment by senhalil** [comment]
Alternatively they should be at least marked as violation of `refute-false` in the first pass.
https://github.com/rubocop-hq/minitest-style-guide#refute-false

This suggests me that there might be a bad interaction between these two cops.

**Comment by senhalil** [comment]
Rubocop returns no offences for the following snippet, but it should complain about the negated asserts. https://github.com/rubocop-hq/minitest-style-guide#refute-false 

```
require 'minitest'
require 'minitest/autorun'
require 'minitest/reporters'
Minitest::Reporters.use!

class MyTest < Minitest::Test
    def test_mytest
        foo = { foo: false }
        assert(!foo.include?(:bar))
        assert(!foo.has_key?(:bar))
        assert(!foo[:foo])
    end
end
```
Since I think they are related I put it here but let me know if you want me to separate them into two issues.

**Comment by koic** [comment]
> Alternatively they should be at least marked as violation of `refute-false` in the first pass.

Thanks for the feedback. I opened the PR #53 to solve the above issue. The `Minitest/RefuteIncludes` cop's issue will be resolved separately.
