### ISSUE TITLE
Support `DEPRECATED: global use of must_equal from ... Use _(obj).must_equal instead. This will fail in Minitest 6.`

### ISSUE THREAD

**Issue by yahonda** [rubocop-hq/rubocop-minitest#60]
## Is your feature request related to a problem? Please describe.

While I'm working on https://github.com/googleapis/google-cloud-ruby/pull/4884 , I've found that to prepare Ruby 3 keyword arguments support, minitest will require https://github.com/seattlerb/minitest/pull/824 .  I think it would mean the newer version of minitest will support Ruby 3. 

On the other hand, gems under `google-cloud-ruby` repository lock the minitest version to use 5.11 or lower because minitest 5.12 shows `DEPRECATED: global use of must_equal from must_equal.rb:28. Use _(obj).must_equal instead. This will fail in Minitest 6.` Refer: https://github.com/seattlerb/minitest/blob/master/History.rdoc#label-5.12.0+-2F+2019-09-22

I'm looking for some way to address this warning automatically to allow bump minitest version when it is ready to support Ruby 3 keyword arguments.

## Describe the solution you'd like

It would be appreciated `rubocop-minitest` gem auto-corrects this warning.

## Describe alternatives you've considered

Rewrite the test code by myself.

## Additional context

Here are the steps to reproduce.

* must_equal.rb
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem 'minitest'
end

# Avoid `Style/Documentation: Missing top-level class documentation comment.`
class Greeting
  def say_hello
    'Hello, World!'
  end

  def say_nothing; end
end

require 'minitest/autorun'
describe Greeting do
  before do
    @foo = Greeting.new
  end

  it 'must say hello world with a warning' do
    # Bad
    @foo.say_hello.must_equal 'Hello, World!'
  end

  it 'must say hello world without warning' do
    # Good
    _(@foo.say_hello).must_equal 'Hello, World!'
  end
end
```

* Result showing `DEPRECATED: global use of must_equal from must_equal.rb:28. Use _(obj).must_equal instead. This will fail in Minitest 6.`

```ruby
% ruby must_equal.rb
Fetching gem metadata from https://rubygems.org/..................
Resolving dependencies...
Using bundler 2.1.2
Using minitest 5.14.0
Run options: --seed 34922

# Running:

DEPRECATED: global use of must_equal from must_equal.rb:28. Use _(obj).must_equal instead. This will fail in Minitest 6.
..

Finished in 0.000651s, 3072.1966 runs/s, 3072.1966 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
% ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
%
```

**Comment by koic** [comment]
I think it is reasonable to respond to official warnings.
