### ISSUE TITLE
Links to documentation are broken

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop-minitest#79]
The GitHub description and README link to https://docs.rubocop.org/projects/minitest which gives a 404, I guess it should point to https://rubocop.readthedocs.io/projects/minitest/en/latest/ ?

**Comment by bbatsov** [comment]
That's WIP - we still haven't integrated it in our new docs site. The old RTD-powered docs will be decommissioned soon.

**Comment by bbatsov** [comment]
The new URL is https://docs.rubocop.org/rubocop-minitest. @koic can you apply the same changes to the other gems? That's the tool I'm using for the conversion of the individual pages - https://github.com/asciidoctor/kramdown-asciidoc

**Comment by koic** [comment]
I get it. I'll take this one later :-)

**Comment by bbatsov** [comment]
Yeah, it's definitely not something urgent. Thanks!

I think we can close this ticket, as things are back to normal for that particular gem. :-)

**Comment by bbatsov** [comment]
P.S. I also updated `rubocop-ast` -> https://docs.rubocop.org/rubocop-ast/index.html

**Comment by andyw8** [comment]
The link in the GitHub header was fixed, but there were still some broken links in the README, so I've opened #80 to fix that.
